### ISSUE TITLE
certificate not valid for v6 subdomain

### ISSUE THREAD

**Issue by 22decembre** [martinp/ipd#15]
Hello and thanks for this usefull service.

The website is available through ifconfig.co and v4.ifconfig.co but not to v6 because the subdomain is not included in the cert.

**Comment by martinp** [comment]
Thanks for reporting this issue.

Unfortunately, this happens because Lets Encrypt does not support challenges for IPv6-only domains. See https://github.com/letsencrypt/letsencrypt/issues/180.

Since `v6.ifconfig.co` exists specifically for IPv6-only lookup, I can't add an A record to pass the Lets Encrypt challenge. Will revisit when Lets Encrypt can handle IPv6 properly.

You need to either use https://ifconfig.co or http://v6.ifconfig.co (without HTTPS).

**Comment by martinp** [comment]
Lets Encrypt has added full support for IPv6: https://letsencrypt.org/2016/07/26/full-ipv6-support.html.

HTTPS is now available for https://v6.ifconfig.co.
