### ISSUE TITLE
User agent filter

### ISSUE THREAD

**Issue by awsum** [martinp/ipd#23]
Why we need UA check on `/ip` and other CLI methods?  Having it for `/` is nice feature, but for specific endpoints it's pretty much useless. Everyone who's not on a list will mimic curl. Anyhow 100% would pass, why to bother?

**Comment by martinp** [comment]
Agreed. The `cliMatcher` should not be used for `/ip`, `/city` and `/country`. I will change it.

**Comment by bfontaine** [comment]
Why is it used at all? You can use the `Accept` header to detect what the client is expecting. My Chrome sends `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`, which becomes "I prefer HTML" in English. cURL doesn’t send such thing.

**Comment by mpolden** [comment]
@bfontaine Because multiple things are served at `/`: Plaintext, JSON and HTML.

It's could perhaps be simplified to:
`Accept` missing => plaintext,
`Accept` is `application/json` => JSON,
`Accept` is anything else => HTML

but then I have to verify that all supported clients always omit the `Accept` header...

**Comment by bfontaine** [comment]
I’ll see if I can test that then make an appropriate pull-request.
